### ISSUE TITLE
Jest types didn't found

### ISSUE THREAD

**Issue by dianjuar** [angular-schule/ngx-deploy-starter#7] opened 2019-09-03 17:15 UTC
When you are writing test, jest types are not found and you miss the auto-completion feature of typescript

To reproduce this bug, just open any test file and see that everything related with jest is not defined

**Comment by JohannesHoppe** [comment] 2019-09-03 18:15
I can confirm that but haven't found the reason until now. Honestly, I ignored the red lines in VSCode vecause the tests still execute flawlessly. Any help is appreciated! ☺️

**Comment by dianjuar** [comment] 2019-09-03 21:33
I have a clone of this repo and there, following an [issue](https://github.com/kulshekhar/ts-jest/issues/889#issuecomment-442703172) I can solve it...

Also, I see that the jest and typescript configurations need a little tweak, it runs the test that are in the dist folder. That means that the typescript compiler is compiling the test and the test runner is searching for test in the dist folder...

**Comment by JohannesHoppe** [comment] 2019-09-03 21:42
Thanks for your investigation. Could you make a PR to fix this?

**Comment by dianjuar** [comment] 2019-09-03 23:24
Sure!

**Comment by JohannesHoppe** [comment] 2019-11-06 19:32
@dianjuar Did you found out how to include the jest types? The red curled lines in VSCode drive me crazy! 😵

**Comment by dianjuar** [comment] 2019-11-07 01:18
Yes I did. I'm not an expert about `tsconfig.json` but did the following

remove ` "files": ["index.ts"],`

and add the following to the end of the file

```json
"exclude": ["node_modules", "dist"],
"typeRoots": ["node_modules/@types"]
```
###### I think the last one was just typescript tweaking and is not related to this issue
---

I lost the reference of the place were I took the solution but was an specific issue related about the types on the test files without a direct solution. Someone on the comments with lots of reactions said something like _ummm, you may have `"files": ["index.ts"]` in your  `tsconfig.json`_  but was almost in a rhetorical way, he was not pointing directly to that solution, so I just removed it, saw that it worked and my development process was not affected at all so I just move forward.

---

I didn't make the PR because I was not sure about how this works, so though _let's wait and see if this comes with a bug or an issue in my project_ but everything is more than fine, my test has their shiny auto-completion and the rest of the project works like a charm.

Maybe you can research more about ` "files": ["index.ts"],` and come with a explanation.

You can compare you `tsconfig.json` with [mine](https://github.com/bikecoders/ngx-deploy-npm/blob/master/src/tsconfig.json)

**Comment by dianjuar** [comment] 2020-12-06 16:29
I think the right way to solve this is to have two separate `tsconfig.json` files, one for development and the other one just for building. I notice this on a nest project and an Angular project, they have separate `tsconfig.json` files, one for development, another for building, and another for testing (this is the Angular case).

I'm also noticing that at the moment of the build it is taking the test files, if some test file has a type problem the build fails.

**Comment by dianjuar** [comment] 2020-12-06 16:42
I'm [migrating my builder to V11](https://github.com/bikecoders/ngx-deploy-npm/issues/27), and I need to do some experiments through TDD, maybe at the end of the integration I have experimented enough to make a PR to solve this

**Comment by JohannesHoppe** [comment] 2020-12-06 16:48
Already fixed in angular-cli-ghpages. I just need some time to port everything back! 😅

**Comment by JohannesHoppe** [comment] 2020-12-06 16:50
https://github.com/angular-schule/angular-cli-ghpages/commit/24d99220c0b443850d8e4ae53c7c99b93da3e53b

**Closed** 2020-12-13 07:56 UTC
